codecov:
  ci:
    - circleci  # track CircleCI builds
    - !heroku   # ignore CI builds by Heroku
coverage:
  range: 50..100 # 50.00% coverage is good, but 100.00% is better
  round: down
  precision: 2
